language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION="3.3.*"

install:
    - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix -vvv --using-cache=no --diff --rules=@Symfony --dry-run --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`