language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - SYMFONY_VERSION="3.3.*"
  - SYMFONY_VERSION="3.4.*"

install:
    - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix -vvv --using-cache=no --diff --config=.php_cs --dry-run --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`